### PR TITLE
Basic .java exporter for vehicles (Flansmod Specific)

### PR DESCRIPTION
**Pull request by GolddolphinSKB-Fexcraftian**
Exported models can now be imported to Toolbox.

To use anything other than Flansmod, the file needs to be modified.

### CODE REVIEW

**Comment by Fexcraft** [comment]
How about calling it "TMT-FLAN-Exporter" then?
I could paste together a general one for e.g. FVTM
which would be called "TMT-FVTM-Exporter".

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Hm... maybe options could be set somehow? Since most of the output code would be the same?
Otherwise it's just a load of copy/paste stuff.

Might be impractical, eh 🤷‍♂️

**Comment by Fexcraft** [comment]
🤔 might research further into JS, iirc you can bind in code from other JS files while processing stuff.

**Comment by GolddolphinSKB-Fexcraftian** [comment]
That sounds rather vile >.<
At least, this exporter would be worth basing the future exporter stuff on.

(The string replacement formats and such)

**Comment by Fexcraft** [comment]
I guess.

**Comment by GolddolphinSKB-Fexcraftian** [comment]
👍

**Pull request merged**
